definitions:
  domain.Chat:
    properties:
      avatar:
        type: string
      id:
        type: string
      name:
        type: string
      users:
        items:
          $ref: '#/definitions/domain.User'
        type: array
    type: object
  domain.User:
    properties:
      bio:
        type: string
      company:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      role:
        type: string
      telegramId:
        type: string
    type: object
info:
  contact: {}
  description: Manage chats, users
  title: TGLinked server
  version: "1.0"
paths:
  /chats:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Chats data
          schema:
            items:
              $ref: '#/definitions/domain.Chat'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get chats for user
      tags:
      - chats
  /chats/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Chat data
          schema:
            $ref: '#/definitions/domain.Chat'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get chat by ID
      tags:
      - chats
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Token
    type: apiKey
swagger: "2.0"
