name: deploy-server

on: 
  workflow_dispatch:

jobs:
  # ci:
  #   uses: ./.github/workflows/ci-server.yaml

  deploy:
    uses: ./.github/workflows/deploy.yaml
    # needs: [ci]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'server/Dockerfile.server'
      context_path: 'server'
      image_name: 'leenky-server'
      environment: 'PROD'
      secret-service-hash: 'SERVER_SERVICE_HASH'
