name: deploy-client

on: 
  workflow_dispatch:

jobs:
  deploy:
    uses: shampsdev/cicd-pipelines/.github/workflows/deploy.yaml@main
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'client/Dockerfile'
      context_path: 'client'
      image_name: 'leenky-client'
      environment: 'PROD'
      secret-service-hash: 'CLIENT_SERVICE_HASH'
