name: deploy-bot

on: 
  workflow_dispatch:


jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'bot'
      context_path: 'bot'
      image_name: 'tglinked-bot'
      environment: 'PROD'
      secret-service-hash: 'BOT_SERVICE_HASH'
