name: deploy-client

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Deploy to DEV/PROD
        type: choice
        options: [DEV, PROD]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'client'
      context_path: 'client'
      image_name: 'tglinked-client'
      environment: ${{ github.event.inputs.environment }}
      secret-service-hash: ${{ github.event.inputs.environment == 'PROD' && 'CLIENT_SERVICE_HASH' || 'CLIENT_SERVICE_HASH_DEV' }}
